import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.navbar}>
        <ul className={styles.categoryList}>
          <li className={styles.categoryItem}>Burger</li>
          <li className={styles.categoryItem}>Lanches</li>
          <li className={styles.categoryItem}>Sucos</li>
          <li className={styles.categoryItem}>Drinks</li>
          <li className={styles.categoryItem}>Outros</li>
          {/* <li className={styles.categoryItem}>Outros</li>
          <li className={styles.categoryItem}>Outros</li>
          <li className={styles.categoryItem}>Outros</li>
          <li className={styles.categoryItem}>Outros</li> */}
        </ul>
      </nav>
      {/* <nav className={styles.banner}>
        <Image src="/img/foodPorn.png" alt="Nosso melhor hambúrger" layout='fill' objectFit='contain' />

      </nav> */}
      <main className={styles.main}>
        <ul className={styles.menu}>
          <li className={styles.dish}>
            <div>
              <h6>Lanche 01 - Burger  01</h6>
              <small>Descrição do Hamburguer</small>
            </div>
          </li>
        </ul>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

